
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_float_0_5;
PyObject *const_float_1_0;
PyObject *const_float_2_0;
PyObject *const_int_neg_1;
PyObject *const_int_neg_2;
PyObject *const_int_neg_4;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_int_pos_9;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_float_2_54;
PyObject *const_int_pos_10;
PyObject *const_int_pos_11;
PyObject *const_int_pos_12;
PyObject *const_int_pos_13;
PyObject *const_int_pos_14;
PyObject *const_int_pos_15;
PyObject *const_int_pos_16;
PyObject *const_int_pos_24;
PyObject *const_int_pos_28;
PyObject *const_int_pos_32;
PyObject *const_int_pos_64;
PyObject *const_str_chr_60;
PyObject *const_str_chr_62;
PyObject *const_bytes_chr_0;
PyObject *const_bytes_empty;
PyObject *const_float_360_0;
PyObject *const_int_pos_100;
PyObject *const_int_pos_128;
PyObject *const_int_pos_255;
PyObject *const_int_pos_256;
PyObject *const_int_pos_270;
PyObject *const_int_pos_282;
PyObject *const_int_pos_296;
PyObject *const_int_pos_320;
PyObject *const_int_pos_322;
PyObject *const_int_pos_323;
PyObject *const_int_pos_512;
PyObject *const_int_pos_768;
PyObject *const_str_plain_1;
PyObject *const_str_plain_A;
PyObject *const_str_plain_B;
PyObject *const_str_plain_F;
PyObject *const_str_plain_I;
PyObject *const_str_plain_L;
PyObject *const_str_plain_P;
PyObject *const_str_plain_a;
PyObject *const_str_plain_b;
PyObject *const_str_plain_c;
PyObject *const_str_plain_d;
PyObject *const_str_plain_e;
PyObject *const_str_plain_f;
PyObject *const_str_plain_g;
PyObject *const_str_plain_i;
PyObject *const_str_plain_j;
PyObject *const_str_plain_k;
PyObject *const_str_plain_l;
PyObject *const_str_plain_m;
PyObject *const_str_plain_n;
PyObject *const_str_plain_o;
PyObject *const_str_plain_p;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_v;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_str_plain_y;
PyObject *const_tuple_empty;
PyObject *const_bytes_chr_35;
PyObject *const_int_pos_1000;
PyObject *const_str_plain_LA;
PyObject *const_str_plain_La;
PyObject *const_str_plain_PA;
PyObject *const_str_plain_fp;
PyObject *const_str_plain_i8;
PyObject *const_str_plain_im;
PyObject *const_str_plain_io;
PyObject *const_str_plain_ix;
PyObject *const_str_plain_o8;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_str_plain_x0;
PyObject *const_str_plain_x1;
PyObject *const_str_plain_xy;
PyObject *const_str_plain_y0;
PyObject *const_str_plain_y1;
PyObject *const_xrange_0_256;
PyObject *const_xrange_0_768;
PyObject *const_bytes_chr_255;
PyObject *const_int_pos_34665;
PyObject *const_int_pos_45057;
PyObject *const_int_pos_45058;
PyObject *const_int_pos_65535;
PyObject *const_int_pos_65536;
PyObject *const_str_plain_BMP;
PyObject *const_str_plain_HSV;
PyObject *const_str_plain_LAB;
PyObject *const_str_plain_PIL;
PyObject *const_str_plain_PNG;
PyObject *const_str_plain_PPM;
PyObject *const_str_plain_RGB;
PyObject *const_str_plain__im;
PyObject *const_str_plain_add;
PyObject *const_str_plain_arr;
PyObject *const_str_plain_cls;
PyObject *const_str_plain_dpi;
PyObject *const_str_plain_elt;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_i16;
PyObject *const_str_plain_i32;
PyObject *const_str_plain_idx;
PyObject *const_str_plain_img;
PyObject *const_str_plain_ims;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_log;
PyObject *const_str_plain_lut;
PyObject *const_str_plain_map;
PyObject *const_str_plain_max;
PyObject *const_str_plain_min;
PyObject *const_str_plain_msg;
PyObject *const_str_plain_new;
PyObject *const_str_plain_num;
PyObject *const_str_plain_o16;
PyObject *const_str_plain_o32;
PyObject *const_str_plain_out;
PyObject *const_str_plain_png;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_pos;
PyObject *const_str_plain_ppm;
PyObject *const_str_plain_raw;
PyObject *const_str_plain_rgb;
PyObject *const_str_plain_sin;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_tag;
PyObject *const_str_plain_typ;
PyObject *const_str_plain_val;
PyObject *const_str_plain_BGRA;
PyObject *const_str_plain_BGRX;
PyObject *const_str_plain_CMYK;
PyObject *const_str_plain_JPEG;
PyObject *const_str_plain_RGBA;
PyObject *const_str_plain_RGBX;
PyObject *const_str_plain_RGBa;
PyObject *const_str_plain_SAVE;
PyObject *const_str_plain__new;
PyObject *const_str_plain_args;
PyObject *const_str_plain_bits;
PyObject *const_str_plain_ceil;
PyObject *const_str_plain_cffi;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_core;
PyObject *const_str_plain_crop;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dest;
PyObject *const_str_plain_file;
PyObject *const_str_plain_fill;
PyObject *const_str_plain_head;
PyObject *const_str_plain_info;
PyObject *const_str_plain_init;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_jpeg;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_line;
PyObject *const_str_plain_load;
PyObject *const_str_plain_mask;
PyObject *const_str_plain_math;
PyObject *const_str_plain_mode;
PyObject *const_str_plain_name;
PyObject *const_str_plain_next;
PyObject *const_str_plain_open;
PyObject *const_str_plain_pack;
PyObject *const_str_plain_path;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_save;
PyObject *const_str_plain_seek;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_show;
PyObject *const_str_plain_site;
PyObject *const_str_plain_size;
PyObject *const_str_plain_sort;
PyObject *const_str_plain_tell;
PyObject *const_str_plain_tile;
PyObject *const_str_plain_type;
PyObject *const_str_plain_vals;
PyObject *const_str_plain_warn;
PyObject *const_int_pos_1048576;
PyObject *const_str_plain_Image;
PyObject *const_str_plain_MODES;
PyObject *const_str_plain_TYPES;
PyObject *const_str_plain_YCbCr;
PyObject *const_str_plain__crop;
PyObject *const_str_plain__dump;
PyObject *const_str_plain__open;
PyObject *const_str_plain__save;
PyObject *const_str_plain__seek;
PyObject *const_str_plain__util;
PyObject *const_str_plain_alpha;
PyObject *const_str_plain_array;
PyObject *const_str_plain_ascii;
PyObject *const_str_plain_bands;
PyObject *const_str_plain_blend;
PyObject *const_str_plain_block;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_chain;
PyObject *const_str_plain_close;
PyObject *const_str_plain_color;
PyObject *const_str_plain_count;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_dirty;
PyObject *const_str_plain_draft;
PyObject *const_str_plain_error;
PyObject *const_str_plain_flush;
PyObject *const_str_plain_frame;
PyObject *const_str_plain_i16be;
PyObject *const_str_plain_i16le;
PyObject *const_str_plain_i32be;
PyObject *const_str_plain_i32le;
PyObject *const_str_plain_image;
PyObject *const_str_plain_index;
PyObject *const_str_plain_items;
PyObject *const_str_plain_layer;
PyObject *const_str_plain_level;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_match;
PyObject *const_str_plain_merge;
PyObject *const_str_plain_o16be;
PyObject *const_str_plain_o16le;
PyObject *const_str_plain_o32be;
PyObject *const_str_plain_o32le;
PyObject *const_str_plain_other;
PyObject *const_str_plain_paste;
PyObject *const_str_plain_pixel;
PyObject *const_str_plain_print;
PyObject *const_str_plain_range;
PyObject *const_str_plain_reset;
PyObject *const_str_plain_round;
PyObject *const_str_plain_scale;
PyObject *const_str_plain_split;
PyObject *const_str_plain_state;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_title;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_wedge;
PyObject *const_str_plain_width;
PyObject *const_str_plain_write;
PyObject *const_str_plain_xsize;
PyObject *const_str_plain_ysize;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_Number;
PyObject *const_str_plain___eq__;
PyObject *const_str_plain__getmp;
PyObject *const_str_plain_access;
PyObject *const_str_plain_append;
PyObject *const_str_plain_buffer;
PyObject *const_str_plain_colors;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_expand;
PyObject *const_str_plain_fileno;
PyObject *const_str_plain_filter;
PyObject *const_str_plain_format;
PyObject *const_str_plain_getrgb;
PyObject *const_str_plain_header;
PyObject *const_str_plain_height;
PyObject *const_str_plain_image1;
PyObject *const_str_plain_image2;
PyObject *const_str_plain_isPath;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_length;
PyObject *const_str_plain_little;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_logger;
PyObject *const_str_plain_lookup;
PyObject *const_str_plain_offset;
PyObject *const_str_plain_params;
PyObject *const_str_plain_pixels;
PyObject *const_str_plain_prefix;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_setter;
PyObject *const_str_plain_sorted;
PyObject *const_str_plain_stdout;
PyObject *const_str_plain_struct;
PyObject *const_str_plain_unlink;
PyObject *const_str_plain_unpack;
PyObject *const_str_plain_update;
PyObject *const_str_plain_verify;
PyObject *const_tuple_none_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_BytesIO;
PyObject *const_str_plain_ImageQt;
PyObject *const_str_plain_RAWMODE;
PyObject *const_str_plain_VERSION;
PyObject *const_str_plain___add__;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___mul__;
PyObject *const_str_plain___new__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain__accept;
PyObject *const_str_plain__binary;
PyObject *const_str_plain_bufsize;
PyObject *const_str_plain_command;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_convert;
PyObject *const_str_plain_current;
PyObject *const_str_plain_decoder;
PyObject *const_str_plain_entries;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_extents;
PyObject *const_str_plain_getbbox;
PyObject *const_str_plain_getdata;
PyObject *const_str_plain_getmode;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_handler;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_logging;
PyObject *const_str_plain_mkstemp;
PyObject *const_str_plain_numbers;
PyObject *const_str_plain_options;
PyObject *const_str_plain_palette;
PyObject *const_str_plain_presets;
PyObject *const_str_plain_quality;
PyObject *const_str_plain_rawmode;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_reverse;
PyObject *const_str_plain_tobytes;
PyObject *const_str_plain_unknown;
PyObject *const_str_plain_version;
PyObject *const_str_plain_xoffset;
PyObject *const_str_plain_yoffset;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_int_pos_1073741824;
PyObject *const_int_pos_2147483648;
PyObject *const_str_plain_ADAPTIVE;
PyObject *const_str_plain_Iterator;
PyObject *const_str_plain_MAXBLOCK;
PyObject *const_str_plain_PyAccess;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain__decoder;
PyObject *const_str_plain__plugins;
PyObject *const_str_plain_basemode;
PyObject *const_str_plain_basetype;
PyObject *const_str_plain_category;
PyObject *const_str_plain_cvt_enum;
PyObject *const_str_plain_endswith;
PyObject *const_str_plain_filename;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_getcolor;
PyObject *const_str_plain_getpixel;
PyObject *const_str_plain_getvalue;
PyObject *const_str_plain_load_end;
PyObject *const_str_plain_mpoffset;
PyObject *const_str_plain_n_frames;
PyObject *const_str_plain_optimize;
PyObject *const_str_plain_putpixel;
PyObject *const_str_plain_readline;
PyObject *const_str_plain_readonly;
PyObject *const_str_plain_register;
PyObject *const_str_plain_save_all;
PyObject *const_str_plain_setimage;
PyObject *const_str_plain_tempfile;
PyObject *const_str_plain_toqimage;
PyObject *const_str_plain_tostring;
PyObject *const_str_plain_warnings;
PyObject *const_str_plain_ImageFile;
PyObject *const_str_plain_SAFEBLOCK;
PyObject *const_str_plain__MAPMODES;
PyObject *const_str_plain__MODEINFO;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain___slots__;
PyObject *const_str_plain__n_frames;
PyObject *const_str_plain__save_all;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_byteorder;
PyObject *const_str_plain_composite;
PyObject *const_str_plain_extension;
PyObject *const_str_plain_getLogger;
PyObject *const_str_plain_histogram;
PyObject *const_str_plain_interlace;
PyObject *const_str_plain_itertools;
PyObject *const_str_plain_load_read;
PyObject *const_str_plain_load_seek;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_toqpixmap;
PyObject *const_str_plain_DataOffset;
PyObject *const_str_plain_ImageColor;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain__safe_read;
PyObject *const_str_plain_background;
PyObject *const_str_plain_check_call;
PyObject *const_str_plain_fromqimage;
PyObject *const_str_plain_getextrema;
PyObject *const_str_plain_getpalette;
PyObject *const_str_plain_map_buffer;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_subprocess;
PyObject *const_str_plain_PaletteFile;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain___setitem__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain__getdecoder;
PyObject *const_str_plain__getencoder;
PyObject *const_str_plain__seek_check;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_collections;
PyObject *const_str_plain_compression;
PyObject *const_str_plain_description;
PyObject *const_str_plain_encoderinfo;
PyObject *const_str_plain_fromqpixmap;
PyObject *const_str_plain_getmodebase;
PyObject *const_str_plain_icc_profile;
PyObject *const_str_plain_is_animated;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_int_pos_2_tuple;
PyObject *const_tuple_int_pos_3_tuple;
PyObject *const_tuple_int_pos_4_tuple;
PyObject *const_tuple_int_pos_8_tuple;
PyObject *const_tuple_none_none_tuple;
PyObject *const_str_plain_ImagePalette;
PyObject *const_str_plain_LIBTIFF_CORE;
PyObject *const_str_plain_MpoImageFile;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain__is_animated;
PyObject *const_str_plain_isStringType;
PyObject *const_str_plain_load_prepare;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_transparency;
PyObject *const_str_plain_version_info;
PyObject *const_str_plain_x_resolution;
PyObject *const_tuple_int_pos_16_tuple;
PyObject *const_str_plain_JpegImageFile;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__exclusive_fp;
PyObject *const_str_plain_append_images;
PyObject *const_str_plain_decoderconfig;
PyObject *const_str_plain_encoderconfig;
PyObject *const_str_plain_palette_bytes;
PyObject *const_str_plain_register_mime;
PyObject *const_str_plain_register_open;
PyObject *const_str_plain_register_save;
PyObject *const_str_plain_remap_palette;
PyObject *const_tuple_bytes_chr_0_tuple;
PyObject *const_tuple_bytes_empty_tuple;
PyObject *const_tuple_int_0_int_0_tuple;
PyObject *const_tuple_int_pos_255_tuple;
PyObject *const_tuple_int_pos_256_tuple;
PyObject *const_tuple_int_pos_322_tuple;
PyObject *const_tuple_int_pos_323_tuple;
PyObject *const_tuple_str_plain_L_tuple;
PyObject *const_tuple_str_plain_b_tuple;
PyObject *const_tuple_str_plain_c_tuple;
PyObject *const_tuple_str_plain_i_tuple;
PyObject *const_tuple_str_plain_t_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_PILLOW_VERSION;
PyObject *const_str_plain_compress_level;
PyObject *const_str_plain_deferred_error;
PyObject *const_str_plain_print_function;
PyObject *const_str_plain_source_palette;
PyObject *const_tuple_str_plain_im_tuple;
PyObject *const_tuple_str_plain_o8_tuple;
PyObject *const_slice_int_pos_1_none_none;
PyObject *const_slice_int_pos_2_none_none;
PyObject *const_slice_int_pos_4_none_none;
PyObject *const_slice_int_pos_6_none_none;
PyObject *const_slice_none_int_pos_2_none;
PyObject *const_slice_none_int_pos_4_none;
PyObject *const_str_angle_dictcontraction;
PyObject *const_str_angle_listcontraction;
PyObject *const_str_plain_GimpPaletteFile;
PyObject *const_str_plain_JpegImagePlugin;
PyObject *const_str_plain_MultibandFilter;
PyObject *const_str_plain_qt_is_installed;
PyObject *const_str_plain_resolution_unit;
PyObject *const_str_plain_subtract_modulo;
PyObject *const_tuple_str_plain_RGB_tuple;
PyObject *const_tuple_str_plain_dpi_tuple;
PyObject *const_slice_int_0_int_pos_1_none;
PyObject *const_slice_int_0_int_pos_2_none;
PyObject *const_slice_none_int_pos_11_none;
PyObject *const_slice_none_int_pos_12_none;
PyObject *const_str_plain_GimpGradientFile;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_RGBA_tuple;
PyObject *const_tuple_str_plain_mode_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_slice_none_int_pos_768_none;
PyObject *const_str_plain_pypy_version_info;
PyObject *const_str_plain_register_save_all;
PyObject *const_tuple_str_plain_Image_tuple;
PyObject *const_tuple_str_plain_ascii_tuple;
PyObject *const_tuple_str_plain_image_tuple;
PyObject *const_tuple_str_plain_value_tuple;
PyObject *const_str_plain_format_description;
PyObject *const_str_plain_register_extension;
PyObject *const_tuple_str_plain_isPath_tuple;
PyObject *const_tuple_str_plain_prefix_tuple;
PyObject *const_str_plain_register_extensions;
PyObject *const_tuple_int_0_int_pos_255_tuple;
PyObject *const_tuple_str_plain_BytesIO_tuple;
PyObject *const_tuple_str_plain_version_tuple;
PyObject *const_slice_int_pos_1_int_pos_3_none;
PyObject *const_slice_int_pos_2_int_pos_4_none;
PyObject *const_slice_int_pos_4_int_pos_6_none;
PyObject *const_slice_int_pos_6_int_pos_8_none;
PyObject *const_str_plain_UnsupportedOperation;
PyObject *const_str_plain_ImageFileDirectory_v1;
PyObject *const_str_plain_ImageFileDirectory_v2;
PyObject *const_str_plain_LOAD_TRUNCATED_IMAGES;
PyObject *const_tuple_int_pos_1_int_pos_1_tuple;
PyObject *const_tuple_int_pos_3_int_pos_3_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_tuple_type_list_type_tuple_tuple;
PyObject *const_tuple_str_plain_icc_profile_tuple;
PyObject *const_str_plain__decompression_bomb_check;
PyObject *const_tuple_str_plain_P_str_plain_P_tuple;
PyObject *const_tuple_tuple_int_0_int_0_tuple_tuple;
PyObject *const_tuple_str_plain_optimize_false_tuple;
PyObject *const_tuple_str_plain_self_str_plain_fp_tuple;
PyObject *const_tuple_str_plain_RGBA_str_plain_RGBa_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_tuple;
PyObject *const_tuple_str_plain_self_str_plain_data_tuple;
PyObject *const_tuple_str_plain_self_str_plain_frame_tuple;
PyObject *const_tuple_str_plain_self_str_plain_image_tuple;
PyObject *const_tuple_str_plain_self_str_plain_other_tuple;
PyObject *const_tuple_str_plain_self_str_plain_value_tuple;
PyObject *const_str_digest_01d1a2f6802fda75c31567b35856fd3e;
PyObject *const_str_digest_084e7b24f5ff6fbbfb31e69f0a2a35d0;
PyObject *const_str_digest_0fde4dc5ce330fdd8e2eb5c008ed370c;
PyObject *const_str_digest_17d69dc3570c8d2bc716ffdcf5eb861e;
PyObject *const_str_digest_19532ebc85912cba7ed62a9cd4e9c195;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_380c2cde6c6849a9cfbcc9225b2b8425;
PyObject *const_str_digest_397c5c7fdc15959b77fa01985509e603;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_5726afd33be7f7234ebf753075902130;
PyObject *const_str_digest_62b7e67e29e99420603c12d205222fa5;
PyObject *const_str_digest_6500339fb9ac37f5860ed740a1224c1b;
PyObject *const_str_digest_668285c8e15fd1c4c777c2ca124e7de4;
PyObject *const_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d;
PyObject *const_str_digest_772c0402ef22c7a4d610f4443976d74a;
PyObject *const_str_digest_8e5335fb02f73f9b285b14387631d654;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a43c96e669182759de7b6dc21baa30ee;
PyObject *const_str_digest_a847edfea52ac2580b31c3747424369d;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_ba53677f9b092c6ca615792cfd270985;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d3a7496dc9671c04c9e24180d49c8edb;
PyObject *const_str_digest_d5fd04dedd0c85d3e5ecf7d4bee2253f;
PyObject *const_str_digest_e22ac7b852354d067e215f51ea4a3592;
PyObject *const_str_digest_ece467abb1e8b5d96ebdfea23136ef86;
PyObject *const_str_digest_f38dff559c7f3c807c14fcb91fa72782;
PyObject *const_str_digest_f3fd79206c841b8bcd38b9a09694c067;
PyObject *const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0;
PyObject *const_str_plain__close_exclusive_fp_after_loading;
PyObject *const_tuple_a3c4d264fc3ef18a3d120a02567f3451_tuple;
PyObject *const_tuple_str_plain_self_str_plain_current_tuple;
PyObject *const_bytes_digest_3d83999277d9e5cf3228587a8fa3a8ce;
PyObject *const_tuple_str_plain_self_str_plain_x_str_plain_y_tuple;
PyObject *const_tuple_str_plain_im_str_plain_fp_str_plain_filename_tuple;
PyObject *const_tuple_str_plain_self_str_plain_mode_str_plain_size_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple;
PyObject *const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_i_tuple;
PyObject *const_tuple_str_plain_P_str_digest_19532ebc85912cba7ed62a9cd4e9c195_tuple;
PyObject *const_tuple_str_plain_P_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d_tuple;
PyObject *const_tuple_str_plain_Image_str_plain_ImageFile_str_plain_ImagePalette_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING( &constant_bin[ 1 ], 1, 0 );
    const_float_0_0 = UNSTREAM_FLOAT( &constant_bin[ 109025 ] );
    const_float_0_5 = UNSTREAM_FLOAT( &constant_bin[ 109033 ] );
    const_float_1_0 = UNSTREAM_FLOAT( &constant_bin[ 109041 ] );
    const_float_2_0 = UNSTREAM_FLOAT( &constant_bin[ 109049 ] );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_neg_2 = PyLong_FromLong( -2l );
    const_int_neg_4 = PyLong_FromLong( -4l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_3 = PyLong_FromUnsignedLong( 3ul );
    const_int_pos_4 = PyLong_FromUnsignedLong( 4ul );
    const_int_pos_5 = PyLong_FromUnsignedLong( 5ul );
    const_int_pos_6 = PyLong_FromUnsignedLong( 6ul );
    const_int_pos_7 = PyLong_FromUnsignedLong( 7ul );
    const_int_pos_8 = PyLong_FromUnsignedLong( 8ul );
    const_int_pos_9 = PyLong_FromUnsignedLong( 9ul );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_float_2_54 = UNSTREAM_FLOAT( &constant_bin[ 109057 ] );
    const_int_pos_10 = PyLong_FromUnsignedLong( 10ul );
    const_int_pos_11 = PyLong_FromUnsignedLong( 11ul );
    const_int_pos_12 = PyLong_FromUnsignedLong( 12ul );
    const_int_pos_13 = PyLong_FromUnsignedLong( 13ul );
    const_int_pos_14 = PyLong_FromUnsignedLong( 14ul );
    const_int_pos_15 = PyLong_FromUnsignedLong( 15ul );
    const_int_pos_16 = PyLong_FromUnsignedLong( 16ul );
    const_int_pos_24 = PyLong_FromUnsignedLong( 24ul );
    const_int_pos_28 = PyLong_FromUnsignedLong( 28ul );
    const_int_pos_32 = PyLong_FromUnsignedLong( 32ul );
    const_int_pos_64 = PyLong_FromUnsignedLong( 64ul );
    const_str_chr_60 = UNSTREAM_STRING( &constant_bin[ 5 ], 1, 0 );
    const_str_chr_62 = UNSTREAM_STRING( &constant_bin[ 16 ], 1, 0 );
    const_bytes_chr_0 = UNSTREAM_BYTES( &constant_bin[ 78 ], 1 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_float_360_0 = UNSTREAM_FLOAT( &constant_bin[ 109065 ] );
    const_int_pos_100 = PyLong_FromUnsignedLong( 100ul );
    const_int_pos_128 = PyLong_FromUnsignedLong( 128ul );
    const_int_pos_255 = PyLong_FromUnsignedLong( 255ul );
    const_int_pos_256 = PyLong_FromUnsignedLong( 256ul );
    const_int_pos_270 = PyLong_FromUnsignedLong( 270ul );
    const_int_pos_282 = PyLong_FromUnsignedLong( 282ul );
    const_int_pos_296 = PyLong_FromUnsignedLong( 296ul );
    const_int_pos_320 = PyLong_FromUnsignedLong( 320ul );
    const_int_pos_322 = PyLong_FromUnsignedLong( 322ul );
    const_int_pos_323 = PyLong_FromUnsignedLong( 323ul );
    const_int_pos_512 = PyLong_FromUnsignedLong( 512ul );
    const_int_pos_768 = PyLong_FromUnsignedLong( 768ul );
    const_str_plain_1 = UNSTREAM_STRING( &constant_bin[ 0 ], 1, 0 );
    const_str_plain_A = UNSTREAM_STRING( &constant_bin[ 865 ], 1, 1 );
    const_str_plain_B = UNSTREAM_STRING( &constant_bin[ 83 ], 1, 1 );
    const_str_plain_F = UNSTREAM_STRING( &constant_bin[ 28 ], 1, 1 );
    const_str_plain_I = UNSTREAM_STRING( &constant_bin[ 14 ], 1, 1 );
    const_str_plain_L = UNSTREAM_STRING( &constant_bin[ 15 ], 1, 1 );
    const_str_plain_P = UNSTREAM_STRING( &constant_bin[ 13 ], 1, 1 );
    const_str_plain_a = UNSTREAM_STRING( &constant_bin[ 25 ], 1, 1 );
    const_str_plain_b = UNSTREAM_STRING( &constant_bin[ 45 ], 1, 1 );
    const_str_plain_c = UNSTREAM_STRING( &constant_bin[ 54 ], 1, 1 );
    const_str_plain_d = UNSTREAM_STRING( &constant_bin[ 8 ], 1, 1 );
    const_str_plain_e = UNSTREAM_STRING( &constant_bin[ 11 ], 1, 1 );
    const_str_plain_f = UNSTREAM_STRING( &constant_bin[ 101 ], 1, 1 );
    const_str_plain_g = UNSTREAM_STRING( &constant_bin[ 23 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING( &constant_bin[ 29 ], 1, 1 );
    const_str_plain_j = UNSTREAM_STRING( &constant_bin[ 2448 ], 1, 1 );
    const_str_plain_k = UNSTREAM_STRING( &constant_bin[ 55 ], 1, 1 );
    const_str_plain_l = UNSTREAM_STRING( &constant_bin[ 10 ], 1, 1 );
    const_str_plain_m = UNSTREAM_STRING( &constant_bin[ 6 ], 1, 1 );
    const_str_plain_n = UNSTREAM_STRING( &constant_bin[ 39 ], 1, 1 );
    const_str_plain_o = UNSTREAM_STRING( &constant_bin[ 7 ], 1, 1 );
    const_str_plain_p = UNSTREAM_STRING( &constant_bin[ 52 ], 1, 1 );
    const_str_plain_r = UNSTREAM_STRING( &constant_bin[ 21 ], 1, 1 );
    const_str_plain_s = UNSTREAM_STRING( &constant_bin[ 32 ], 1, 1 );
    const_str_plain_t = UNSTREAM_STRING( &constant_bin[ 36 ], 1, 1 );
    const_str_plain_v = UNSTREAM_STRING( &constant_bin[ 939 ], 1, 1 );
    const_str_plain_w = UNSTREAM_STRING( &constant_bin[ 849 ], 1, 1 );
    const_str_plain_x = UNSTREAM_STRING( &constant_bin[ 138 ], 1, 1 );
    const_str_plain_y = UNSTREAM_STRING( &constant_bin[ 35 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_bytes_chr_35 = UNSTREAM_BYTES( &constant_bin[ 6258 ], 1 );
    const_int_pos_1000 = PyLong_FromUnsignedLong( 1000ul );
    const_str_plain_LA = UNSTREAM_STRING( &constant_bin[ 17970 ], 2, 1 );
    const_str_plain_La = UNSTREAM_STRING( &constant_bin[ 71641 ], 2, 1 );
    const_str_plain_PA = UNSTREAM_STRING( &constant_bin[ 49320 ], 2, 1 );
    const_str_plain_fp = UNSTREAM_STRING( &constant_bin[ 3834 ], 2, 1 );
    const_str_plain_i8 = UNSTREAM_STRING( &constant_bin[ 109073 ], 2, 1 );
    const_str_plain_im = UNSTREAM_STRING( &constant_bin[ 1532 ], 2, 1 );
    const_str_plain_io = UNSTREAM_STRING( &constant_bin[ 1329 ], 2, 1 );
    const_str_plain_ix = UNSTREAM_STRING( &constant_bin[ 595 ], 2, 1 );
    const_str_plain_o8 = UNSTREAM_STRING( &constant_bin[ 109075 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 3241 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 53697 ], 2, 1 );
    const_str_plain_re = UNSTREAM_STRING( &constant_bin[ 882 ], 2, 1 );
    const_str_plain_x0 = UNSTREAM_STRING( &constant_bin[ 24520 ], 2, 1 );
    const_str_plain_x1 = UNSTREAM_STRING( &constant_bin[ 14585 ], 2, 1 );
    const_str_plain_xy = UNSTREAM_STRING( &constant_bin[ 15972 ], 2, 1 );
    const_str_plain_y0 = UNSTREAM_STRING( &constant_bin[ 24524 ], 2, 1 );
    const_str_plain_y1 = UNSTREAM_STRING( &constant_bin[ 24532 ], 2, 1 );
    const_xrange_0_256 = BUILTIN_XRANGE3( const_int_0, const_int_pos_256, const_int_pos_1 );
    const_xrange_0_768 = BUILTIN_XRANGE3( const_int_0, const_int_pos_768, const_int_pos_1 );
    const_bytes_chr_255 = UNSTREAM_BYTES( &constant_bin[ 1032 ], 1 );
    const_int_pos_34665 = PyLong_FromUnsignedLong( 34665ul );
    const_int_pos_45057 = PyLong_FromUnsignedLong( 45057ul );
    const_int_pos_45058 = PyLong_FromUnsignedLong( 45058ul );
    const_int_pos_65535 = PyLong_FromUnsignedLong( 65535ul );
    const_int_pos_65536 = PyLong_FromUnsignedLong( 65536ul );
    const_str_plain_BMP = UNSTREAM_STRING( &constant_bin[ 909 ], 3, 1 );
    const_str_plain_HSV = UNSTREAM_STRING( &constant_bin[ 5995 ], 3, 1 );
    const_str_plain_LAB = UNSTREAM_STRING( &constant_bin[ 38083 ], 3, 1 );
    const_str_plain_PIL = UNSTREAM_STRING( &constant_bin[ 13 ], 3, 1 );
    const_str_plain_PNG = UNSTREAM_STRING( &constant_bin[ 33082 ], 3, 1 );
    const_str_plain_PPM = UNSTREAM_STRING( &constant_bin[ 48404 ], 3, 1 );
    const_str_plain_RGB = UNSTREAM_STRING( &constant_bin[ 1636 ], 3, 1 );
    const_str_plain__im = UNSTREAM_STRING( &constant_bin[ 3704 ], 3, 1 );
    const_str_plain_add = UNSTREAM_STRING( &constant_bin[ 875 ], 3, 1 );
    const_str_plain_arr = UNSTREAM_STRING( &constant_bin[ 20050 ], 3, 1 );
    const_str_plain_cls = UNSTREAM_STRING( &constant_bin[ 86459 ], 3, 1 );
    const_str_plain_dpi = UNSTREAM_STRING( &constant_bin[ 73706 ], 3, 1 );
    const_str_plain_elt = UNSTREAM_STRING( &constant_bin[ 3837 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 3725 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 2652 ], 3, 1 );
    const_str_plain_i16 = UNSTREAM_STRING( &constant_bin[ 108333 ], 3, 1 );
    const_str_plain_i32 = UNSTREAM_STRING( &constant_bin[ 107614 ], 3, 1 );
    const_str_plain_idx = UNSTREAM_STRING( &constant_bin[ 90808 ], 3, 1 );
    const_str_plain_img = UNSTREAM_STRING( &constant_bin[ 54215 ], 3, 1 );
    const_str_plain_ims = UNSTREAM_STRING( &constant_bin[ 9352 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 4130 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 9365 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 4634 ], 3, 1 );
    const_str_plain_log = UNSTREAM_STRING( &constant_bin[ 12261 ], 3, 1 );
    const_str_plain_lut = UNSTREAM_STRING( &constant_bin[ 26393 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 1275 ], 3, 1 );
    const_str_plain_max = UNSTREAM_STRING( &constant_bin[ 8787 ], 3, 1 );
    const_str_plain_min = UNSTREAM_STRING( &constant_bin[ 2307 ], 3, 1 );
    const_str_plain_msg = UNSTREAM_STRING( &constant_bin[ 109077 ], 3, 1 );
    const_str_plain_new = UNSTREAM_STRING( &constant_bin[ 6904 ], 3, 1 );
    const_str_plain_num = UNSTREAM_STRING( &constant_bin[ 1223 ], 3, 1 );
    const_str_plain_o16 = UNSTREAM_STRING( &constant_bin[ 109080 ], 3, 1 );
    const_str_plain_o32 = UNSTREAM_STRING( &constant_bin[ 68804 ], 3, 1 );
    const_str_plain_out = UNSTREAM_STRING( &constant_bin[ 951 ], 3, 1 );
    const_str_plain_png = UNSTREAM_STRING( &constant_bin[ 20964 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 103698 ], 3, 1 );
    const_str_plain_pos = UNSTREAM_STRING( &constant_bin[ 3240 ], 3, 1 );
    const_str_plain_ppm = UNSTREAM_STRING( &constant_bin[ 2577 ], 3, 1 );
    const_str_plain_raw = UNSTREAM_STRING( &constant_bin[ 847 ], 3, 1 );
    const_str_plain_rgb = UNSTREAM_STRING( &constant_bin[ 989 ], 3, 1 );
    const_str_plain_sin = UNSTREAM_STRING( &constant_bin[ 2349 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 7930 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 56324 ], 3, 1 );
    const_str_plain_tag = UNSTREAM_STRING( &constant_bin[ 90491 ], 3, 1 );
    const_str_plain_typ = UNSTREAM_STRING( &constant_bin[ 1795 ], 3, 1 );
    const_str_plain_val = UNSTREAM_STRING( &constant_bin[ 12089 ], 3, 1 );
    const_str_plain_BGRA = UNSTREAM_STRING( &constant_bin[ 1666 ], 4, 1 );
    const_str_plain_BGRX = UNSTREAM_STRING( &constant_bin[ 1934 ], 4, 1 );
    const_str_plain_CMYK = UNSTREAM_STRING( &constant_bin[ 18610 ], 4, 1 );
    const_str_plain_JPEG = UNSTREAM_STRING( &constant_bin[ 14530 ], 4, 1 );
    const_str_plain_RGBA = UNSTREAM_STRING( &constant_bin[ 1658 ], 4, 1 );
    const_str_plain_RGBX = UNSTREAM_STRING( &constant_bin[ 18590 ], 4, 1 );
    const_str_plain_RGBa = UNSTREAM_STRING( &constant_bin[ 92483 ], 4, 1 );
    const_str_plain_SAVE = UNSTREAM_STRING( &constant_bin[ 24765 ], 4, 1 );
    const_str_plain__new = UNSTREAM_STRING( &constant_bin[ 13540 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 14193 ], 4, 1 );
    const_str_plain_bits = UNSTREAM_STRING( &constant_bin[ 3856 ], 4, 1 );
    const_str_plain_ceil = UNSTREAM_STRING( &constant_bin[ 92200 ], 4, 1 );
    const_str_plain_cffi = UNSTREAM_STRING( &constant_bin[ 109083 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 6974 ], 4, 1 );
    const_str_plain_core = UNSTREAM_STRING( &constant_bin[ 12784 ], 4, 1 );
    const_str_plain_crop = UNSTREAM_STRING( &constant_bin[ 20426 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 843 ], 4, 1 );
    const_str_plain_dest = UNSTREAM_STRING( &constant_bin[ 9358 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING( &constant_bin[ 827 ], 4, 1 );
    const_str_plain_fill = UNSTREAM_STRING( &constant_bin[ 10598 ], 4, 1 );
    const_str_plain_head = UNSTREAM_STRING( &constant_bin[ 836 ], 4, 1 );
    const_str_plain_info = UNSTREAM_STRING( &constant_bin[ 832 ], 4, 1 );
    const_str_plain_init = UNSTREAM_STRING( &constant_bin[ 67 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 3328 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 109087 ], 4, 1 );
    const_str_plain_jpeg = UNSTREAM_STRING( &constant_bin[ 71124 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 109091 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING( &constant_bin[ 5975 ], 4, 1 );
    const_str_plain_load = UNSTREAM_STRING( &constant_bin[ 3720 ], 4, 1 );
    const_str_plain_mask = UNSTREAM_STRING( &constant_bin[ 965 ], 4, 1 );
    const_str_plain_math = UNSTREAM_STRING( &constant_bin[ 109095 ], 4, 1 );
    const_str_plain_mode = UNSTREAM_STRING( &constant_bin[ 851 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 6704 ], 4, 1 );
    const_str_plain_next = UNSTREAM_STRING( &constant_bin[ 3396 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 1012 ], 4, 1 );
    const_str_plain_pack = UNSTREAM_STRING( &constant_bin[ 52 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 11147 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 1234 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 2695 ], 4, 1 );
    const_str_plain_save = UNSTREAM_STRING( &constant_bin[ 2174 ], 4, 1 );
    const_str_plain_seek = UNSTREAM_STRING( &constant_bin[ 2599 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 25969 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING( &constant_bin[ 94608 ], 4, 1 );
    const_str_plain_show = UNSTREAM_STRING( &constant_bin[ 33442 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 47 ], 4, 1 );
    const_str_plain_size = UNSTREAM_STRING( &constant_bin[ 1311 ], 4, 1 );
    const_str_plain_sort = UNSTREAM_STRING( &constant_bin[ 43877 ], 4, 1 );
    const_str_plain_tell = UNSTREAM_STRING( &constant_bin[ 3319 ], 4, 1 );
    const_str_plain_tile = UNSTREAM_STRING( &constant_bin[ 57151 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 1795 ], 4, 1 );
    const_str_plain_vals = UNSTREAM_STRING( &constant_bin[ 84265 ], 4, 1 );
    const_str_plain_warn = UNSTREAM_STRING( &constant_bin[ 17667 ], 4, 1 );
    const_int_pos_1048576 = PyLong_FromUnsignedLong( 1048576ul );
    const_str_plain_Image = UNSTREAM_STRING( &constant_bin[ 86 ], 5, 1 );
    const_str_plain_MODES = UNSTREAM_STRING( &constant_bin[ 869 ], 5, 1 );
    const_str_plain_TYPES = UNSTREAM_STRING( &constant_bin[ 95817 ], 5, 1 );
    const_str_plain_YCbCr = UNSTREAM_STRING( &constant_bin[ 38049 ], 5, 1 );
    const_str_plain__crop = UNSTREAM_STRING( &constant_bin[ 27924 ], 5, 1 );
    const_str_plain__dump = UNSTREAM_STRING( &constant_bin[ 41165 ], 5, 1 );
    const_str_plain__open = UNSTREAM_STRING( &constant_bin[ 1011 ], 5, 1 );
    const_str_plain__save = UNSTREAM_STRING( &constant_bin[ 2173 ], 5, 1 );
    const_str_plain__seek = UNSTREAM_STRING( &constant_bin[ 2598 ], 5, 1 );
    const_str_plain__util = UNSTREAM_STRING( &constant_bin[ 108381 ], 5, 1 );
    const_str_plain_alpha = UNSTREAM_STRING( &constant_bin[ 11672 ], 5, 1 );
    const_str_plain_array = UNSTREAM_STRING( &constant_bin[ 20050 ], 5, 1 );
    const_str_plain_ascii = UNSTREAM_STRING( &constant_bin[ 109099 ], 5, 1 );
    const_str_plain_bands = UNSTREAM_STRING( &constant_bin[ 6763 ], 5, 1 );
    const_str_plain_blend = UNSTREAM_STRING( &constant_bin[ 47244 ], 5, 1 );
    const_str_plain_block = UNSTREAM_STRING( &constant_bin[ 20833 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 3417 ], 5, 1 );
    const_str_plain_chain = UNSTREAM_STRING( &constant_bin[ 109104 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 6412 ], 5, 1 );
    const_str_plain_color = UNSTREAM_STRING( &constant_bin[ 3206 ], 5, 1 );
    const_str_plain_count = UNSTREAM_STRING( &constant_bin[ 3694 ], 5, 1 );
    const_str_plain_debug = UNSTREAM_STRING( &constant_bin[ 41844 ], 5, 1 );
    const_str_plain_dirty = UNSTREAM_STRING( &constant_bin[ 109109 ], 5, 1 );
    const_str_plain_draft = UNSTREAM_STRING( &constant_bin[ 26158 ], 5, 1 );
    const_str_plain_error = UNSTREAM_STRING( &constant_bin[ 41888 ], 5, 1 );
    const_str_plain_flush = UNSTREAM_STRING( &constant_bin[ 109114 ], 5, 1 );
    const_str_plain_frame = UNSTREAM_STRING( &constant_bin[ 2572 ], 5, 1 );
    const_str_plain_i16be = UNSTREAM_STRING( &constant_bin[ 109119 ], 5, 1 );
    const_str_plain_i16le = UNSTREAM_STRING( &constant_bin[ 108333 ], 5, 1 );
    const_str_plain_i32be = UNSTREAM_STRING( &constant_bin[ 109124 ], 5, 1 );
    const_str_plain_i32le = UNSTREAM_STRING( &constant_bin[ 107614 ], 5, 1 );
    const_str_plain_image = UNSTREAM_STRING( &constant_bin[ 1532 ], 5, 1 );
    const_str_plain_index = UNSTREAM_STRING( &constant_bin[ 2504 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING( &constant_bin[ 5406 ], 5, 1 );
    const_str_plain_layer = UNSTREAM_STRING( &constant_bin[ 12789 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 25354 ], 5, 1 );
    const_str_plain_lower = UNSTREAM_STRING( &constant_bin[ 20304 ], 5, 1 );
    const_str_plain_match = UNSTREAM_STRING( &constant_bin[ 14424 ], 5, 1 );
    const_str_plain_merge = UNSTREAM_STRING( &constant_bin[ 109129 ], 5, 1 );
    const_str_plain_o16be = UNSTREAM_STRING( &constant_bin[ 109134 ], 5, 1 );
    const_str_plain_o16le = UNSTREAM_STRING( &constant_bin[ 109139 ], 5, 1 );
    const_str_plain_o32be = UNSTREAM_STRING( &constant_bin[ 109144 ], 5, 1 );
    const_str_plain_o32le = UNSTREAM_STRING( &constant_bin[ 109149 ], 5, 1 );
    const_str_plain_other = UNSTREAM_STRING( &constant_bin[ 3021 ], 5, 1 );
    const_str_plain_paste = UNSTREAM_STRING( &constant_bin[ 15753 ], 5, 1 );
    const_str_plain_pixel = UNSTREAM_STRING( &constant_bin[ 913 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING( &constant_bin[ 21430 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 12170 ], 5, 1 );
    const_str_plain_reset = UNSTREAM_STRING( &constant_bin[ 57402 ], 5, 1 );
    const_str_plain_round = UNSTREAM_STRING( &constant_bin[ 7108 ], 5, 1 );
    const_str_plain_scale = UNSTREAM_STRING( &constant_bin[ 885 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 25818 ], 5, 1 );
    const_str_plain_state = UNSTREAM_STRING( &constant_bin[ 29053 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING( &constant_bin[ 109154 ], 5, 1 );
    const_str_plain_title = UNSTREAM_STRING( &constant_bin[ 48812 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING( &constant_bin[ 20096 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 12089 ], 5, 1 );
    const_str_plain_wedge = UNSTREAM_STRING( &constant_bin[ 40616 ], 5, 1 );
    const_str_plain_width = UNSTREAM_STRING( &constant_bin[ 9207 ], 5, 1 );
    const_str_plain_write = UNSTREAM_STRING( &constant_bin[ 1396 ], 5, 1 );
    const_str_plain_xsize = UNSTREAM_STRING( &constant_bin[ 99045 ], 5, 1 );
    const_str_plain_ysize = UNSTREAM_STRING( &constant_bin[ 99052 ], 5, 1 );
    const_str_angle_lambda = UNSTREAM_STRING( &constant_bin[ 1861 ], 8, 0 );
    const_str_plain_Number = UNSTREAM_STRING( &constant_bin[ 45467 ], 6, 1 );
    const_str_plain___eq__ = UNSTREAM_STRING( &constant_bin[ 41810 ], 6, 1 );
    const_str_plain__getmp = UNSTREAM_STRING( &constant_bin[ 74027 ], 6, 1 );
    const_str_plain_access = UNSTREAM_STRING( &constant_bin[ 15251 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 84358 ], 6, 1 );
    const_str_plain_buffer = UNSTREAM_STRING( &constant_bin[ 8300 ], 6, 1 );
    const_str_plain_colors = UNSTREAM_STRING( &constant_bin[ 3231 ], 6, 1 );
    const_str_plain_decode = UNSTREAM_STRING( &constant_bin[ 8462 ], 6, 1 );
    const_str_plain_encode = UNSTREAM_STRING( &constant_bin[ 2470 ], 6, 1 );
    const_str_plain_expand = UNSTREAM_STRING( &constant_bin[ 7665 ], 6, 1 );
    const_str_plain_fileno = UNSTREAM_STRING( &constant_bin[ 90642 ], 6, 1 );
    const_str_plain_filter = UNSTREAM_STRING( &constant_bin[ 7227 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 1751 ], 6, 1 );
    const_str_plain_getrgb = UNSTREAM_STRING( &constant_bin[ 56506 ], 6, 1 );
    const_str_plain_header = UNSTREAM_STRING( &constant_bin[ 836 ], 6, 1 );
    const_str_plain_height = UNSTREAM_STRING( &constant_bin[ 9214 ], 6, 1 );
    const_str_plain_image1 = UNSTREAM_STRING( &constant_bin[ 11696 ], 6, 1 );
    const_str_plain_image2 = UNSTREAM_STRING( &constant_bin[ 11721 ], 6, 1 );
    const_str_plain_isPath = UNSTREAM_STRING( &constant_bin[ 109159 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 109165 ], 6, 1 );
    const_str_plain_length = UNSTREAM_STRING( &constant_bin[ 40607 ], 6, 1 );
    const_str_plain_little = UNSTREAM_STRING( &constant_bin[ 109171 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 1853 ], 6, 1 );
    const_str_plain_logger = UNSTREAM_STRING( &constant_bin[ 109177 ], 6, 1 );
    const_str_plain_lookup = UNSTREAM_STRING( &constant_bin[ 46438 ], 6, 1 );
    const_str_plain_offset = UNSTREAM_STRING( &constant_bin[ 2932 ], 6, 1 );
    const_str_plain_params = UNSTREAM_STRING( &constant_bin[ 2996 ], 6, 1 );
    const_str_plain_pixels = UNSTREAM_STRING( &constant_bin[ 1886 ], 6, 1 );
    const_str_plain_prefix = UNSTREAM_STRING( &constant_bin[ 21971 ], 6, 1 );
    const_str_plain_remove = UNSTREAM_STRING( &constant_bin[ 36941 ], 6, 1 );
    const_str_plain_setter = UNSTREAM_STRING( &constant_bin[ 109183 ], 6, 1 );
    const_str_plain_sorted = UNSTREAM_STRING( &constant_bin[ 43877 ], 6, 1 );
    const_str_plain_stdout = UNSTREAM_STRING( &constant_bin[ 109189 ], 6, 1 );
    const_str_plain_struct = UNSTREAM_STRING( &constant_bin[ 22369 ], 6, 1 );
    const_str_plain_unlink = UNSTREAM_STRING( &constant_bin[ 109195 ], 6, 1 );
    const_str_plain_unpack = UNSTREAM_STRING( &constant_bin[ 16249 ], 6, 1 );
    const_str_plain_update = UNSTREAM_STRING( &constant_bin[ 5649 ], 6, 1 );
    const_str_plain_verify = UNSTREAM_STRING( &constant_bin[ 36480 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 4469 ], 9, 0 );
    const_str_plain_BytesIO = UNSTREAM_STRING( &constant_bin[ 16602 ], 7, 1 );
    const_str_plain_ImageQt = UNSTREAM_STRING( &constant_bin[ 68784 ], 7, 1 );
    const_str_plain_RAWMODE = UNSTREAM_STRING( &constant_bin[ 4278 ], 7, 1 );
    const_str_plain_VERSION = UNSTREAM_STRING( &constant_bin[ 109201 ], 7, 1 );
    const_str_plain___add__ = UNSTREAM_STRING( &constant_bin[ 25342 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 109208 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 109215 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 109222 ], 7, 1 );
    const_str_plain___mul__ = UNSTREAM_STRING( &constant_bin[ 20121 ], 7, 1 );
    const_str_plain___new__ = UNSTREAM_STRING( &constant_bin[ 85220 ], 7, 1 );
    const_str_plain___str__ = UNSTREAM_STRING( &constant_bin[ 65387 ], 7, 1 );
    const_str_plain__accept = UNSTREAM_STRING( &constant_bin[ 29074 ], 7, 1 );
    const_str_plain__binary = UNSTREAM_STRING( &constant_bin[ 107623 ], 7, 1 );
    const_str_plain_bufsize = UNSTREAM_STRING( &constant_bin[ 57608 ], 7, 1 );
    const_str_plain_command = UNSTREAM_STRING( &constant_bin[ 48905 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 17520 ], 7, 1 );
    const_str_plain_convert = UNSTREAM_STRING( &constant_bin[ 4065 ], 7, 1 );
    const_str_plain_current = UNSTREAM_STRING( &constant_bin[ 12746 ], 7, 1 );
    const_str_plain_decoder = UNSTREAM_STRING( &constant_bin[ 8462 ], 7, 1 );
    const_str_plain_entries = UNSTREAM_STRING( &constant_bin[ 2408 ], 7, 1 );
    const_str_plain_environ = UNSTREAM_STRING( &constant_bin[ 7403 ], 7, 1 );
    const_str_plain_extents = UNSTREAM_STRING( &constant_bin[ 58165 ], 7, 1 );
    const_str_plain_getbbox = UNSTREAM_STRING( &constant_bin[ 37484 ], 7, 1 );
    const_str_plain_getdata = UNSTREAM_STRING( &constant_bin[ 3618 ], 7, 1 );
    const_str_plain_getmode = UNSTREAM_STRING( &constant_bin[ 9398 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 109229 ], 7, 1 );
    const_str_plain_handler = UNSTREAM_STRING( &constant_bin[ 34086 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 109236 ], 7, 1 );
    const_str_plain_logging = UNSTREAM_STRING( &constant_bin[ 109243 ], 7, 1 );
    const_str_plain_mkstemp = UNSTREAM_STRING( &constant_bin[ 109250 ], 7, 1 );
    const_str_plain_numbers = UNSTREAM_STRING( &constant_bin[ 95345 ], 7, 1 );
    const_str_plain_options = UNSTREAM_STRING( &constant_bin[ 38711 ], 7, 1 );
    const_str_plain_palette = UNSTREAM_STRING( &constant_bin[ 1370 ], 7, 1 );
    const_str_plain_presets = UNSTREAM_STRING( &constant_bin[ 81033 ], 7, 1 );
    const_str_plain_quality = UNSTREAM_STRING( &constant_bin[ 34358 ], 7, 1 );
    const_str_plain_rawmode = UNSTREAM_STRING( &constant_bin[ 27843 ], 7, 1 );
    const_str_plain_replace = UNSTREAM_STRING( &constant_bin[ 17859 ], 7, 1 );
    const_str_plain_reverse = UNSTREAM_STRING( &constant_bin[ 88527 ], 7, 1 );
    const_str_plain_tobytes = UNSTREAM_STRING( &constant_bin[ 29166 ], 7, 1 );
    const_str_plain_unknown = UNSTREAM_STRING( &constant_bin[ 9373 ], 7, 1 );
    const_str_plain_version = UNSTREAM_STRING( &constant_bin[ 13872 ], 7, 1 );
    const_str_plain_xoffset = UNSTREAM_STRING( &constant_bin[ 49696 ], 7, 1 );
    const_str_plain_yoffset = UNSTREAM_STRING( &constant_bin[ 49639 ], 7, 1 );
    const_tuple_false_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_int_pos_1073741824 = PyLong_FromUnsignedLong( 1073741824ul );
    const_int_pos_2147483648 = PyLong_FromUnsignedLong( 2147483648ul );
    const_str_plain_ADAPTIVE = UNSTREAM_STRING( &constant_bin[ 45434 ], 8, 1 );
    const_str_plain_Iterator = UNSTREAM_STRING( &constant_bin[ 69467 ], 8, 1 );
    const_str_plain_MAXBLOCK = UNSTREAM_STRING( &constant_bin[ 109257 ], 8, 1 );
    const_str_plain_PyAccess = UNSTREAM_STRING( &constant_bin[ 15443 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 109265 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 47176 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 109273 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 65 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 69576 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 109281 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 109289 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 109297 ], 8, 1 );
    const_str_plain___repr__ = UNSTREAM_STRING( &constant_bin[ 43597 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING( &constant_bin[ 109305 ], 8, 1 );
    const_str_plain__decoder = UNSTREAM_STRING( &constant_bin[ 16089 ], 8, 1 );
    const_str_plain__plugins = UNSTREAM_STRING( &constant_bin[ 109313 ], 8, 1 );
    const_str_plain_basemode = UNSTREAM_STRING( &constant_bin[ 109321 ], 8, 1 );
    const_str_plain_basetype = UNSTREAM_STRING( &constant_bin[ 93947 ], 8, 1 );
    const_str_plain_category = UNSTREAM_STRING( &constant_bin[ 85526 ], 8, 1 );
    const_str_plain_cvt_enum = UNSTREAM_STRING( &constant_bin[ 100248 ], 8, 1 );
    const_str_plain_endswith = UNSTREAM_STRING( &constant_bin[ 109329 ], 8, 1 );
    const_str_plain_filename = UNSTREAM_STRING( &constant_bin[ 11128 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 109337 ], 8, 1 );
    const_str_plain_getcolor = UNSTREAM_STRING( &constant_bin[ 8494 ], 8, 1 );
    const_str_plain_getpixel = UNSTREAM_STRING( &constant_bin[ 36913 ], 8, 1 );
    const_str_plain_getvalue = UNSTREAM_STRING( &constant_bin[ 90652 ], 8, 1 );
    const_str_plain_load_end = UNSTREAM_STRING( &constant_bin[ 3720 ], 8, 1 );
    const_str_plain_mpoffset = UNSTREAM_STRING( &constant_bin[ 83180 ], 8, 1 );
    const_str_plain_n_frames = UNSTREAM_STRING( &constant_bin[ 5697 ], 8, 1 );
    const_str_plain_optimize = UNSTREAM_STRING( &constant_bin[ 2338 ], 8, 1 );
    const_str_plain_putpixel = UNSTREAM_STRING( &constant_bin[ 20916 ], 8, 1 );
    const_str_plain_readline = UNSTREAM_STRING( &constant_bin[ 109345 ], 8, 1 );
    const_str_plain_readonly = UNSTREAM_STRING( &constant_bin[ 58129 ], 8, 1 );
    const_str_plain_register = UNSTREAM_STRING( &constant_bin[ 9311 ], 8, 1 );
    const_str_plain_save_all = UNSTREAM_STRING( &constant_bin[ 109353 ], 8, 1 );
    const_str_plain_setimage = UNSTREAM_STRING( &constant_bin[ 57287 ], 8, 1 );
    const_str_plain_tempfile = UNSTREAM_STRING( &constant_bin[ 109361 ], 8, 1 );
    const_str_plain_toqimage = UNSTREAM_STRING( &constant_bin[ 23791 ], 8, 1 );
    const_str_plain_tostring = UNSTREAM_STRING( &constant_bin[ 33908 ], 8, 1 );
    const_str_plain_warnings = UNSTREAM_STRING( &constant_bin[ 109369 ], 8, 1 );
    const_str_plain_ImageFile = UNSTREAM_STRING( &constant_bin[ 1001 ], 9, 1 );
    const_str_plain_SAFEBLOCK = UNSTREAM_STRING( &constant_bin[ 58439 ], 9, 1 );
    const_str_plain__MAPMODES = UNSTREAM_STRING( &constant_bin[ 109377 ], 9, 1 );
    const_str_plain__MODEINFO = UNSTREAM_STRING( &constant_bin[ 109386 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 109395 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 29066 ], 9, 1 );
    const_str_plain___slots__ = UNSTREAM_STRING( &constant_bin[ 109404 ], 9, 1 );
    const_str_plain__n_frames = UNSTREAM_STRING( &constant_bin[ 109413 ], 9, 1 );
    const_str_plain__save_all = UNSTREAM_STRING( &constant_bin[ 109422 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 68059 ], 9, 1 );
    const_str_plain_byteorder = UNSTREAM_STRING( &constant_bin[ 109431 ], 9, 1 );
    const_str_plain_composite = UNSTREAM_STRING( &constant_bin[ 12280 ], 9, 1 );
    const_str_plain_extension = UNSTREAM_STRING( &constant_bin[ 3593 ], 9, 1 );
    const_str_plain_getLogger = UNSTREAM_STRING( &constant_bin[ 109440 ], 9, 1 );
    const_str_plain_histogram = UNSTREAM_STRING( &constant_bin[ 32118 ], 9, 1 );
    const_str_plain_interlace = UNSTREAM_STRING( &constant_bin[ 5587 ], 9, 1 );
    const_str_plain_itertools = UNSTREAM_STRING( &constant_bin[ 109449 ], 9, 1 );
    const_str_plain_load_read = UNSTREAM_STRING( &constant_bin[ 87255 ], 9, 1 );
    const_str_plain_load_seek = UNSTREAM_STRING( &constant_bin[ 83074 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING( &constant_bin[ 109458 ], 9, 1 );
    const_str_plain_toqpixmap = UNSTREAM_STRING( &constant_bin[ 33865 ], 9, 1 );
    const_str_plain_DataOffset = UNSTREAM_STRING( &constant_bin[ 109467 ], 10, 1 );
    const_str_plain_ImageColor = UNSTREAM_STRING( &constant_bin[ 13383 ], 10, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING( &constant_bin[ 109477 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 109487 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING( &constant_bin[ 109497 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 109507 ], 10, 1 );
    const_str_plain__safe_read = UNSTREAM_STRING( &constant_bin[ 109517 ], 10, 1 );
    const_str_plain_background = UNSTREAM_STRING( &constant_bin[ 109527 ], 10, 1 );
    const_str_plain_check_call = UNSTREAM_STRING( &constant_bin[ 109537 ], 10, 1 );
    const_str_plain_fromqimage = UNSTREAM_STRING( &constant_bin[ 109547 ], 10, 1 );
    const_str_plain_getextrema = UNSTREAM_STRING( &constant_bin[ 20786 ], 10, 1 );
    const_str_plain_getpalette = UNSTREAM_STRING( &constant_bin[ 6024 ], 10, 1 );
    const_str_plain_map_buffer = UNSTREAM_STRING( &constant_bin[ 109557 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 109567 ], 10, 1 );
    const_str_plain_subprocess = UNSTREAM_STRING( &constant_bin[ 109577 ], 10, 1 );
    const_str_plain_PaletteFile = UNSTREAM_STRING( &constant_bin[ 6208 ], 11, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 13567 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING( &constant_bin[ 69519 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 109587 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING( &constant_bin[ 109598 ], 11, 1 );
    const_str_plain___setitem__ = UNSTREAM_STRING( &constant_bin[ 89490 ], 11, 1 );
    const_str_plain___version__ = UNSTREAM_STRING( &constant_bin[ 109609 ], 11, 1 );
    const_str_plain__getdecoder = UNSTREAM_STRING( &constant_bin[ 109620 ], 11, 1 );
    const_str_plain__getencoder = UNSTREAM_STRING( &constant_bin[ 109631 ], 11, 1 );
    const_str_plain__seek_check = UNSTREAM_STRING( &constant_bin[ 57770 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 109642 ], 11, 1 );
    const_str_plain_collections = UNSTREAM_STRING( &constant_bin[ 109653 ], 11, 1 );
    const_str_plain_compression = UNSTREAM_STRING( &constant_bin[ 1348 ], 11, 1 );
    const_str_plain_description = UNSTREAM_STRING( &constant_bin[ 109664 ], 11, 1 );
    const_str_plain_encoderinfo = UNSTREAM_STRING( &constant_bin[ 2470 ], 11, 1 );
    const_str_plain_fromqpixmap = UNSTREAM_STRING( &constant_bin[ 109675 ], 11, 1 );
    const_str_plain_getmodebase = UNSTREAM_STRING( &constant_bin[ 109686 ], 11, 1 );
    const_str_plain_icc_profile = UNSTREAM_STRING( &constant_bin[ 73775 ], 11, 1 );
    const_str_plain_is_animated = UNSTREAM_STRING( &constant_bin[ 5794 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_pos_2_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_tuple, 0, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    const_tuple_int_pos_3_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_int_pos_4_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_4_tuple, 0, const_int_pos_4 ); Py_INCREF( const_int_pos_4 );
    const_tuple_int_pos_8_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_8_tuple, 0, const_int_pos_8 ); Py_INCREF( const_int_pos_8 );
    const_tuple_none_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_str_plain_ImagePalette = UNSTREAM_STRING( &constant_bin[ 65502 ], 12, 1 );
    const_str_plain_LIBTIFF_CORE = UNSTREAM_STRING( &constant_bin[ 109697 ], 12, 1 );
    const_str_plain_MpoImageFile = UNSTREAM_STRING( &constant_bin[ 82863 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 109709 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 109721 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING( &constant_bin[ 109733 ], 12, 1 );
    const_str_plain__is_animated = UNSTREAM_STRING( &constant_bin[ 109745 ], 12, 1 );
    const_str_plain_isStringType = UNSTREAM_STRING( &constant_bin[ 109757 ], 12, 1 );
    const_str_plain_load_prepare = UNSTREAM_STRING( &constant_bin[ 57229 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 109769 ], 12, 1 );
    const_str_plain_transparency = UNSTREAM_STRING( &constant_bin[ 6645 ], 12, 1 );
    const_str_plain_version_info = UNSTREAM_STRING( &constant_bin[ 109781 ], 12, 1 );
    const_str_plain_x_resolution = UNSTREAM_STRING( &constant_bin[ 109793 ], 12, 1 );
    const_tuple_int_pos_16_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_16_tuple, 0, const_int_pos_16 ); Py_INCREF( const_int_pos_16 );
    const_str_plain_JpegImageFile = UNSTREAM_STRING( &constant_bin[ 73009 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 109805 ], 13, 1 );
    const_str_plain__exclusive_fp = UNSTREAM_STRING( &constant_bin[ 20967 ], 13, 1 );
    const_str_plain_append_images = UNSTREAM_STRING( &constant_bin[ 109818 ], 13, 1 );
    const_str_plain_decoderconfig = UNSTREAM_STRING( &constant_bin[ 109831 ], 13, 1 );
    const_str_plain_encoderconfig = UNSTREAM_STRING( &constant_bin[ 109844 ], 13, 1 );
    const_str_plain_palette_bytes = UNSTREAM_STRING( &constant_bin[ 3487 ], 13, 1 );
    const_str_plain_register_mime = UNSTREAM_STRING( &constant_bin[ 109857 ], 13, 1 );
    const_str_plain_register_open = UNSTREAM_STRING( &constant_bin[ 109870 ], 13, 1 );
    const_str_plain_register_save = UNSTREAM_STRING( &constant_bin[ 109883 ], 13, 1 );
    const_str_plain_remap_palette = UNSTREAM_STRING( &constant_bin[ 46257 ], 13, 1 );
    const_tuple_bytes_chr_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_bytes_chr_0_tuple, 0, const_bytes_chr_0 ); Py_INCREF( const_bytes_chr_0 );
    const_tuple_bytes_empty_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_bytes_empty_tuple, 0, const_bytes_empty ); Py_INCREF( const_bytes_empty );
    const_tuple_int_0_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_int_pos_255_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_255_tuple, 0, const_int_pos_255 ); Py_INCREF( const_int_pos_255 );
    const_tuple_int_pos_256_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_256_tuple, 0, const_int_pos_256 ); Py_INCREF( const_int_pos_256 );
    const_tuple_int_pos_322_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_322_tuple, 0, const_int_pos_322 ); Py_INCREF( const_int_pos_322 );
    const_tuple_int_pos_323_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_323_tuple, 0, const_int_pos_323 ); Py_INCREF( const_int_pos_323 );
    const_tuple_str_plain_L_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_L_tuple, 0, const_str_plain_L ); Py_INCREF( const_str_plain_L );
    const_tuple_str_plain_b_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_b_tuple, 0, const_str_plain_b ); Py_INCREF( const_str_plain_b );
    const_tuple_str_plain_c_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_c_tuple, 0, const_str_plain_c ); Py_INCREF( const_str_plain_c );
    const_tuple_str_plain_i_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_i_tuple, 0, const_str_plain_i ); Py_INCREF( const_str_plain_i );
    const_tuple_str_plain_t_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_t_tuple, 0, const_str_plain_t ); Py_INCREF( const_str_plain_t );
    const_tuple_str_plain_x_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_x_tuple, 0, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain_PILLOW_VERSION = UNSTREAM_STRING( &constant_bin[ 109896 ], 14, 1 );
    const_str_plain_compress_level = UNSTREAM_STRING( &constant_bin[ 109910 ], 14, 1 );
    const_str_plain_deferred_error = UNSTREAM_STRING( &constant_bin[ 108354 ], 14, 1 );
    const_str_plain_print_function = UNSTREAM_STRING( &constant_bin[ 109924 ], 14, 1 );
    const_str_plain_source_palette = UNSTREAM_STRING( &constant_bin[ 10767 ], 14, 1 );
    const_tuple_str_plain_im_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_im_tuple, 0, const_str_plain_im ); Py_INCREF( const_str_plain_im );
    const_tuple_str_plain_o8_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_o8_tuple, 0, const_str_plain_o8 ); Py_INCREF( const_str_plain_o8 );
    const_slice_int_pos_1_none_none = PySlice_New( const_int_pos_1, Py_None, Py_None );
    const_slice_int_pos_2_none_none = PySlice_New( const_int_pos_2, Py_None, Py_None );
    const_slice_int_pos_4_none_none = PySlice_New( const_int_pos_4, Py_None, Py_None );
    const_slice_int_pos_6_none_none = PySlice_New( const_int_pos_6, Py_None, Py_None );
    const_slice_none_int_pos_2_none = PySlice_New( Py_None, const_int_pos_2, Py_None );
    const_slice_none_int_pos_4_none = PySlice_New( Py_None, const_int_pos_4, Py_None );
    const_str_angle_dictcontraction = UNSTREAM_STRING( &constant_bin[ 109938 ], 17, 0 );
    const_str_angle_listcontraction = UNSTREAM_STRING( &constant_bin[ 109955 ], 17, 0 );
    const_str_plain_GimpPaletteFile = UNSTREAM_STRING( &constant_bin[ 6204 ], 15, 1 );
    const_str_plain_JpegImagePlugin = UNSTREAM_STRING( &constant_bin[ 409 ], 15, 1 );
    const_str_plain_MultibandFilter = UNSTREAM_STRING( &constant_bin[ 109972 ], 15, 1 );
    const_str_plain_qt_is_installed = UNSTREAM_STRING( &constant_bin[ 109987 ], 15, 1 );
    const_str_plain_resolution_unit = UNSTREAM_STRING( &constant_bin[ 110002 ], 15, 1 );
    const_str_plain_subtract_modulo = UNSTREAM_STRING( &constant_bin[ 52377 ], 15, 1 );
    const_tuple_str_plain_RGB_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_RGB_tuple, 0, const_str_plain_RGB ); Py_INCREF( const_str_plain_RGB );
    const_tuple_str_plain_dpi_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_dpi_tuple, 0, const_str_plain_dpi ); Py_INCREF( const_str_plain_dpi );
    const_slice_int_0_int_pos_1_none = PySlice_New( const_int_0, const_int_pos_1, Py_None );
    const_slice_int_0_int_pos_2_none = PySlice_New( const_int_0, const_int_pos_2, Py_None );
    const_slice_none_int_pos_11_none = PySlice_New( Py_None, const_int_pos_11, Py_None );
    const_slice_none_int_pos_12_none = PySlice_New( Py_None, const_int_pos_12, Py_None );
    const_str_plain_GimpGradientFile = UNSTREAM_STRING( &constant_bin[ 6111 ], 16, 1 );
    const_tuple_none_none_none_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 2, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_plain_RGBA_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_RGBA_tuple, 0, const_str_plain_RGBA ); Py_INCREF( const_str_plain_RGBA );
    const_tuple_str_plain_mode_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_mode_tuple, 0, const_str_plain_mode ); Py_INCREF( const_str_plain_mode );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_slice_none_int_pos_768_none = PySlice_New( Py_None, const_int_pos_768, Py_None );
    const_str_plain_pypy_version_info = UNSTREAM_STRING( &constant_bin[ 110017 ], 17, 1 );
    const_str_plain_register_save_all = UNSTREAM_STRING( &constant_bin[ 110034 ], 17, 1 );
    const_tuple_str_plain_Image_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Image_tuple, 0, const_str_plain_Image ); Py_INCREF( const_str_plain_Image );
    const_tuple_str_plain_ascii_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_ascii_tuple, 0, const_str_plain_ascii ); Py_INCREF( const_str_plain_ascii );
    const_tuple_str_plain_image_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_image_tuple, 0, const_str_plain_image ); Py_INCREF( const_str_plain_image );
    const_tuple_str_plain_value_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_value_tuple, 0, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_plain_format_description = UNSTREAM_STRING( &constant_bin[ 110051 ], 18, 1 );
    const_str_plain_register_extension = UNSTREAM_STRING( &constant_bin[ 110069 ], 18, 1 );
    const_tuple_str_plain_isPath_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_isPath_tuple, 0, const_str_plain_isPath ); Py_INCREF( const_str_plain_isPath );
    const_tuple_str_plain_prefix_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_prefix_tuple, 0, const_str_plain_prefix ); Py_INCREF( const_str_plain_prefix );
    const_str_plain_register_extensions = UNSTREAM_STRING( &constant_bin[ 110087 ], 19, 1 );
    const_tuple_int_0_int_pos_255_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_255_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_255_tuple, 1, const_int_pos_255 ); Py_INCREF( const_int_pos_255 );
    const_tuple_str_plain_BytesIO_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_BytesIO_tuple, 0, const_str_plain_BytesIO ); Py_INCREF( const_str_plain_BytesIO );
    const_tuple_str_plain_version_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_version_tuple, 0, const_str_plain_version ); Py_INCREF( const_str_plain_version );
    const_slice_int_pos_1_int_pos_3_none = PySlice_New( const_int_pos_1, const_int_pos_3, Py_None );
    const_slice_int_pos_2_int_pos_4_none = PySlice_New( const_int_pos_2, const_int_pos_4, Py_None );
    const_slice_int_pos_4_int_pos_6_none = PySlice_New( const_int_pos_4, const_int_pos_6, Py_None );
    const_slice_int_pos_6_int_pos_8_none = PySlice_New( const_int_pos_6, const_int_pos_8, Py_None );
    const_str_plain_UnsupportedOperation = UNSTREAM_STRING( &constant_bin[ 110106 ], 20, 1 );
    const_str_plain_ImageFileDirectory_v1 = UNSTREAM_STRING( &constant_bin[ 91886 ], 21, 1 );
    const_str_plain_ImageFileDirectory_v2 = UNSTREAM_STRING( &constant_bin[ 90600 ], 21, 1 );
    const_str_plain_LOAD_TRUNCATED_IMAGES = UNSTREAM_STRING( &constant_bin[ 110126 ], 21, 1 );
    const_tuple_int_pos_1_int_pos_1_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_pos_1_tuple, 1, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_pos_3_int_pos_3_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_int_pos_3_tuple, 1, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_tuple_type_list_type_tuple_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_type_list_type_tuple_tuple, 0, (PyObject *)&PyList_Type ); Py_INCREF( (PyObject *)&PyList_Type );
    PyTuple_SET_ITEM( const_tuple_type_list_type_tuple_tuple, 1, (PyObject *)&PyTuple_Type ); Py_INCREF( (PyObject *)&PyTuple_Type );
    const_tuple_str_plain_icc_profile_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_icc_profile_tuple, 0, const_str_plain_icc_profile ); Py_INCREF( const_str_plain_icc_profile );
    const_str_plain__decompression_bomb_check = UNSTREAM_STRING( &constant_bin[ 110147 ], 25, 1 );
    const_tuple_str_plain_P_str_plain_P_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_plain_P_tuple, 0, const_str_plain_P ); Py_INCREF( const_str_plain_P );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_plain_P_tuple, 1, const_str_plain_P ); Py_INCREF( const_str_plain_P );
    const_tuple_tuple_int_0_int_0_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_0_tuple_tuple, 0, const_tuple_int_0_int_0_tuple ); Py_INCREF( const_tuple_int_0_int_0_tuple );
    const_tuple_str_plain_optimize_false_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_optimize_false_tuple, 0, const_str_plain_optimize ); Py_INCREF( const_str_plain_optimize );
    PyTuple_SET_ITEM( const_tuple_str_plain_optimize_false_tuple, 1, Py_False ); Py_INCREF( Py_False );
    const_tuple_str_plain_self_str_plain_fp_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_fp_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_fp_tuple, 1, const_str_plain_fp ); Py_INCREF( const_str_plain_fp );
    const_tuple_str_plain_RGBA_str_plain_RGBa_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_RGBA_str_plain_RGBa_tuple, 0, const_str_plain_RGBA ); Py_INCREF( const_str_plain_RGBA );
    PyTuple_SET_ITEM( const_tuple_str_plain_RGBA_str_plain_RGBa_tuple, 1, const_str_plain_RGBa ); Py_INCREF( const_str_plain_RGBa );
    const_tuple_str_plain_self_str_plain_args_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    const_tuple_str_plain_self_str_plain_data_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 1, const_str_plain_data ); Py_INCREF( const_str_plain_data );
    const_tuple_str_plain_self_str_plain_frame_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_frame_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_frame_tuple, 1, const_str_plain_frame ); Py_INCREF( const_str_plain_frame );
    const_tuple_str_plain_self_str_plain_image_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_image_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_image_tuple, 1, const_str_plain_image ); Py_INCREF( const_str_plain_image );
    const_tuple_str_plain_self_str_plain_other_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 1, const_str_plain_other ); Py_INCREF( const_str_plain_other );
    const_tuple_str_plain_self_str_plain_value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 1, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_digest_01d1a2f6802fda75c31567b35856fd3e = UNSTREAM_STRING( &constant_bin[ 110172 ], 3, 0 );
    const_str_digest_084e7b24f5ff6fbbfb31e69f0a2a35d0 = UNSTREAM_STRING( &constant_bin[ 30560 ], 5, 0 );
    const_str_digest_0fde4dc5ce330fdd8e2eb5c008ed370c = UNSTREAM_STRING( &constant_bin[ 30363 ], 4, 0 );
    const_str_digest_17d69dc3570c8d2bc716ffdcf5eb861e = UNSTREAM_STRING( &constant_bin[ 20924 ], 5, 0 );
    const_str_digest_19532ebc85912cba7ed62a9cd4e9c195 = UNSTREAM_STRING( &constant_bin[ 85823 ], 3, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 21462 ], 2, 0 );
    const_str_digest_380c2cde6c6849a9cfbcc9225b2b8425 = UNSTREAM_STRING( &constant_bin[ 30428 ], 5, 0 );
    const_str_digest_397c5c7fdc15959b77fa01985509e603 = UNSTREAM_STRING( &constant_bin[ 30461 ], 6, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 2445 ], 7, 0 );
    const_str_digest_5726afd33be7f7234ebf753075902130 = UNSTREAM_STRING( &constant_bin[ 37652 ], 5, 0 );
    const_str_digest_62b7e67e29e99420603c12d205222fa5 = UNSTREAM_STRING( &constant_bin[ 84058 ], 7, 0 );
    const_str_digest_6500339fb9ac37f5860ed740a1224c1b = UNSTREAM_STRING( &constant_bin[ 110175 ], 3, 0 );
    const_str_digest_668285c8e15fd1c4c777c2ca124e7de4 = UNSTREAM_STRING( &constant_bin[ 30593 ], 6, 0 );
    const_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d = UNSTREAM_STRING( &constant_bin[ 85785 ], 3, 0 );
    const_str_digest_772c0402ef22c7a4d610f4443976d74a = UNSTREAM_STRING( &constant_bin[ 30395 ], 5, 0 );
    const_str_digest_8e5335fb02f73f9b285b14387631d654 = UNSTREAM_STRING( &constant_bin[ 110178 ], 2, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 110180 ], 46, 0 );
    const_str_digest_a43c96e669182759de7b6dc21baa30ee = UNSTREAM_STRING( &constant_bin[ 90558 ], 3, 0 );
    const_str_digest_a847edfea52ac2580b31c3747424369d = UNSTREAM_STRING( &constant_bin[ 30527 ], 5, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 110226 ], 47, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 5609 ], 2, 1 );
    const_str_digest_ba53677f9b092c6ca615792cfd270985 = UNSTREAM_STRING( &constant_bin[ 110273 ], 36, 0 );
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING( &constant_bin[ 110309 ], 5, 0 );
    const_str_digest_d3a7496dc9671c04c9e24180d49c8edb = UNSTREAM_STRING( &constant_bin[ 110314 ], 40, 0 );
    const_str_digest_d5fd04dedd0c85d3e5ecf7d4bee2253f = UNSTREAM_STRING( &constant_bin[ 110354 ], 16, 0 );
    const_str_digest_e22ac7b852354d067e215f51ea4a3592 = UNSTREAM_STRING( &constant_bin[ 110370 ], 22, 0 );
    const_str_digest_ece467abb1e8b5d96ebdfea23136ef86 = UNSTREAM_STRING( &constant_bin[ 110392 ], 21, 0 );
    const_str_digest_f38dff559c7f3c807c14fcb91fa72782 = UNSTREAM_STRING( &constant_bin[ 110413 ], 27, 0 );
    const_str_digest_f3fd79206c841b8bcd38b9a09694c067 = UNSTREAM_STRING( &constant_bin[ 110440 ], 24, 0 );
    const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0 = UNSTREAM_STRING( &constant_bin[ 110464 ], 48, 0 );
    const_str_plain__close_exclusive_fp_after_loading = UNSTREAM_STRING( &constant_bin[ 110512 ], 33, 1 );
    const_tuple_a3c4d264fc3ef18a3d120a02567f3451_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_a3c4d264fc3ef18a3d120a02567f3451_tuple, 0, const_str_digest_62b7e67e29e99420603c12d205222fa5 ); Py_INCREF( const_str_digest_62b7e67e29e99420603c12d205222fa5 );
    PyTuple_SET_ITEM( const_tuple_a3c4d264fc3ef18a3d120a02567f3451_tuple, 1, const_str_plain_replace ); Py_INCREF( const_str_plain_replace );
    const_tuple_str_plain_self_str_plain_current_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_current_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_current_tuple, 1, const_str_plain_current ); Py_INCREF( const_str_plain_current );
    const_bytes_digest_3d83999277d9e5cf3228587a8fa3a8ce = UNSTREAM_BYTES( &constant_bin[ 110545 ], 4 );
    const_tuple_str_plain_self_str_plain_x_str_plain_y_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_x_str_plain_y_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_x_str_plain_y_tuple, 1, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_x_str_plain_y_tuple, 2, const_str_plain_y ); Py_INCREF( const_str_plain_y );
    const_tuple_str_plain_im_str_plain_fp_str_plain_filename_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_im_str_plain_fp_str_plain_filename_tuple, 0, const_str_plain_im ); Py_INCREF( const_str_plain_im );
    PyTuple_SET_ITEM( const_tuple_str_plain_im_str_plain_fp_str_plain_filename_tuple, 1, const_str_plain_fp ); Py_INCREF( const_str_plain_fp );
    PyTuple_SET_ITEM( const_tuple_str_plain_im_str_plain_fp_str_plain_filename_tuple, 2, const_str_plain_filename ); Py_INCREF( const_str_plain_filename );
    const_tuple_str_plain_self_str_plain_mode_str_plain_size_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_size_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_size_tuple, 1, const_str_plain_mode ); Py_INCREF( const_str_plain_mode );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_size_tuple, 2, const_str_plain_size ); Py_INCREF( const_str_plain_size );
    const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 2, const_str_plain_kwargs ); Py_INCREF( const_str_plain_kwargs );
    const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_i_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_i_tuple, 0, const_str_digest_b9c4baf879ebd882d40843df3a4dead7 ); Py_INCREF( const_str_digest_b9c4baf879ebd882d40843df3a4dead7 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_i_tuple, 1, const_str_plain_i ); Py_INCREF( const_str_plain_i );
    const_tuple_str_plain_P_str_digest_19532ebc85912cba7ed62a9cd4e9c195_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_digest_19532ebc85912cba7ed62a9cd4e9c195_tuple, 0, const_str_plain_P ); Py_INCREF( const_str_plain_P );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_digest_19532ebc85912cba7ed62a9cd4e9c195_tuple, 1, const_str_digest_19532ebc85912cba7ed62a9cd4e9c195 ); Py_INCREF( const_str_digest_19532ebc85912cba7ed62a9cd4e9c195 );
    const_tuple_str_plain_P_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d_tuple, 0, const_str_plain_P ); Py_INCREF( const_str_plain_P );
    PyTuple_SET_ITEM( const_tuple_str_plain_P_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d_tuple, 1, const_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d ); Py_INCREF( const_str_digest_676e11a5ff7d2b82b18a5b0dbbad6c6d );
    const_tuple_str_plain_Image_str_plain_ImageFile_str_plain_ImagePalette_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Image_str_plain_ImageFile_str_plain_ImagePalette_tuple, 0, const_str_plain_Image ); Py_INCREF( const_str_plain_Image );
    PyTuple_SET_ITEM( const_tuple_str_plain_Image_str_plain_ImageFile_str_plain_ImagePalette_tuple, 1, const_str_plain_ImageFile ); Py_INCREF( const_str_plain_ImageFile );
    PyTuple_SET_ITEM( const_tuple_str_plain_Image_str_plain_ImageFile_str_plain_ImagePalette_tuple, 2, const_str_plain_ImagePalette ); Py_INCREF( const_str_plain_ImagePalette );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_ba53677f9b092c6ca615792cfd270985
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
